#!/usr/bin/env python3

import os
import subprocess

os.chdir(os.path.dirname(os.path.realpath(__file__)))

subprocess.check_call(["tsc"])

with open("output/exercise-timer.js", "r") as js, open("src/index.html.in") as html:
    result = html.read().replace("@SCRIPT@", js.read())

with open("output/index.html", "w") as output:
    output.write(result)
